# Generated by Django 3.2 on 2021-06-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_alter_inquiry_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='owner_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
