# Generated by Django 3.2 on 2021-06-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210611_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
